// Generated by CoffeeScript 1.7.1
var Animated;

Animated = (function() {
  function Animated() {
    $("head").append("<style id=\"animated-styles\"></style>");
    this.elements = this.getElements();
    this.writeStyles();
  }

  Animated.prototype.getElements = function() {
    var elements;
    elements = $("*[data-animated-property]");
    return elements;
  };

  Animated.prototype.canAnimate = function(element) {
    if (element.data("animated-property") === undefined) {
      return false;
    }
    if (element.data("animated-from") === undefined) {
      return false;
    }
    if (element.data("animated-to") === undefined) {
      return false;
    }
    if (element.prop("id") === undefined) {
      return false;
    }
    return true;
  };

  Animated.prototype.writeStyles = function() {
    var animationName, css, cssString, el, from, i, property, selector, to;
    i = 0;
    while (i < this.elements.length) {
      el = this.elements.eq(i);
      if (this.canAnimate(el)) {
        selector = '#' + el.prop("id");
        animationName = el.prop("id") + "-animation";
        property = el.data("animated-property");
        from = el.data("animated-from");
        to = el.data("animated-to");
        $("#animated-styles").append("@keyframes " + property + "-animation { from { " + from + "; } to { " + to + "; } }");
        css = [];
        css.push(selector + ' { ');
        css.push('-webkit-animation: ' + animationName + ' 1s linear 1s 1 forward;');
        css.push('-moz-animation: ' + animationName + ' 1s linear 1s 1 forward;');
        css.push('-o-animation: ' + animationName + ' 1s linear 1s 1 forward;');
        css.push('animation: ' + animationName + ' 1s linear 1s 1 forward;');
        css.push(property + ':' + from + ';');
        css.push('}');
        cssString = css.join('\r\n');
        $("#animated-styles").append(cssString);
      }
      return;
    }
  };

  Animated.Animated = Animated;

  return Animated;

})();
